# Generated by Django 3.2.5 on 2021-07-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('about', models.TextField(blank=True, default='NULL', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bookname', models.CharField(default='NULL', max_length=255, null=True, unique=True)),
                ('publication', models.CharField(max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('instances', models.IntegerField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.author')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('y', 'yes'), ('n', 'no')], default='n', help_text='Approval status by librarian', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('o', 'On loan'), ('a', 'Available')], default='a', help_text='Book availability', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.book')),
            ],
        ),
    ]
