# Generated by Django 3.2.4 on 2021-07-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('code', models.AutoField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('bookname', models.CharField(default='NULL', max_length=255, null=True, unique=True)),
                ('publication', models.CharField(max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('instances', models.IntegerField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.author')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('libid', models.AutoField(primary_key=True, serialize=False)),
                ('regno', models.IntegerField(blank=True, default='NULL', null=True)),
                ('branch', models.CharField(blank=True, default='NULL', max_length=255, null=True)),
                ('section', models.CharField(blank=True, default='NULL', max_length=2, null=True)),
                ('semester', models.CharField(blank=True, default='NULL', max_length=255, null=True)),
                ('yearofadm', models.CharField(blank=True, default='NULL', max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('o', 'On loan'), ('a', 'Available')], default='a', help_text='Book availability', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.book')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.student')),
            ],
        ),
    ]
