# Generated by Django 3.2.5 on 2021-07-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookname',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
