# Generated by Django 3.2.5 on 2021-07-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210709_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='status',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, help_text='Is the book available?'),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, help_text='Approval status by librarian'),
        ),
    ]
