# Generated by Django 3.2.5 on 2021-07-17 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_bookinstance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='instances',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateField()),
                ('due_on', models.DateField()),
                ('returned', models.BooleanField(blank=True, default=None, help_text='Has the book been returned?')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.book')),
                ('instancne', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.bookinstance')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
