# Generated by Django 3.2.4 on 2021-07-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_book_instances'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('libid', models.AutoField(primary_key=True, serialize=False)),
                ('regno', models.IntegerField(blank=True, default=None, null=True)),
                ('teamname', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
