# Generated by Django 3.2.4 on 2021-07-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='libid',
            new_name='mentorid',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='regno',
        ),
        migrations.AddField(
            model_name='mentor',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
