# Generated by Django 3.2.4 on 2021-07-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210716_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('libid', models.AutoField(primary_key=True, serialize=False)),
                ('regno', models.IntegerField(blank=True, default=None, null=True)),
                ('branch', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('section', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('semester', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('yearofadm', models.CharField(blank=True, default=None, max_length=5, null=True)),
            ],
        ),
    ]
