# Generated by Django 3.2.4 on 2021-07-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210717_2227'),
        ('api', '0009_student'),
    ]

    operations = [
    ]
