# Generated by Django 3.2.4 on 2021-07-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_history_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libid', models.IntegerField()),
                ('regno', models.IntegerField(blank=True, default=None, null=True)),
                ('branch', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('section', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('semester', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('yearofadm', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
