# Generated by Django 3.2.5 on 2021-07-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='returned_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
