# Generated by Django 3.2.5 on 2021-07-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='regno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
