# Generated by Django 3.2.5 on 2021-07-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='section',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='semester',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='yearofadm',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
